version: "3.7"
# Set -arch=_aarch64 for arm build
services:
  redis:
    build:
      context: .
      args:
#        - arch=_aarch64
        - version=5.0.5
        - build=dev
    image: leadstec/redis:5.0.5
    ports:
      - "50231:6379"
    volumes:
      - ~/volumes-data/redis.local/log:/data/log
      - ~/volumes-data/redis.local/db:/data/db
      - ~/volumes-data/redis.local/persist:/data/persist
    env_file:
      - ./env
    environment:
      - EMAIL=
      - LCS_LOG_LEVEL=debug
    secrets:
      - lcs
    hostname: redis.local
    container_name: redis.local

secrets:
  lcs:
    file: ~/.vcubi/lcs
